### PR TITLE
Update ExternalPluginUpdates.xml

### PR DESCRIPTION
**Pull request by frankbits**
Added "The Disambiguator"-Plugin

Currently not working, as the VERSION-File shows new Version as 1.0.4, but latest release is 1.0.3.

### CODE REVIEW

**Comment by frankbits** [comment]
VERSION of the "The Disambiguator" is now correct, but Update still not working.

**Comment by Rookiestyle** [comment]
What do you mean with "but Update still not working"?

**Comment by frankbits** [comment]
> What do you mean with "but Update still not working"?

most probably I did configure something wrong

In Keepass it correctly shows "The Disambiguator" as to be updated but clicking on Update doesn't update it...

**Comment by Rookiestyle** [comment]
You can activate debug mode before trying to update and attach the debug file that will be created when you close KeePass

https://github.com/Rookiestyle/EarlyUpdateCheck/wiki/Create-a-debugfile#gui-plugin-options

**Comment by Rookiestyle** [comment]
I found it.

You defined the download URL as `...v{MAJOR}.{MINOR}.{BUILD}.{REVISION}/Disambiguator-v{MAJOR}.{MINOR}.{BUILD}.{REVISION}.zip` and AllowVersionStripping as true which means a revision of 0 will be skipped.

The current version is 1.0.4.0 and due to AllowVersionStripping the result string would be v1.0.4./Disambiguator-v1.0.4..zip

Unfortunately changing AllowVersionStripping to false won't help...
KeePass shows the new version as 1.0.4 and this is the only chance for my plugin to know the new version.
Since this is 1.0.4 instead of 1.0.4.0, it won't work.
I'ld try to download Disambiguator-v1.0.4.zip (AllowVersionStripping = true) or Disambiguator-v1.0.4.-1.zip (AllowVersionStripping = false and the undefined revision being translated as -1)


KeePass shows it as 1.0.4 because that's what is mentioned in the plugin's version file https://github.com/drventure/Disambiguator/blob/master/VERSION

The only way to make it work is if the plugin author makes the version file used by KeePass match the filename somehow

**Comment by frankbits** [comment]
I would have thought that AllowVersionStripping would try both, with and without `.0`.

And why isn't the default for `revision` `0`? wouldn't that make more sense?

**Comment by Rookiestyle** [comment]
> I would have thought that AllowVersionStripping would try both, with and without `.0`.
> 
> And why isn't the default for `revision` `0`? wouldn't that make more sense? Because afaik 1.1.1.0 and 1.1.1 should have the same meaning...🤔

I analyzed a bit more.
KeePass never shows the revision if it is 0.
Whether I publish a plugin as version 1.2.3 or 1.2.3.0 doesn't matter, it will be shown as 1.2.3 either way.
If I publish it as 1.2.3.4, it will be shown as 1.2.3.4 

AllowVersionStripping skips revision, build, minor if it's < 1. 
I do not plan to add trying multiple files; you could also argue that 1, 1.1, 1.1.0 and 1.1.1.0 should have the same meaning...
I still do believe that the filename of the zip does not match the version information. If the filename was v1.0.4 it would match and I'ld be able to download it.

As of now, for this very plugin the sole benefit of EarlyUpdateCheck is, that you are informed about a new version BEFORE you entered your masterkey. The feature to auto-update this plugin is not possible.

**Comment by Rookiestyle** [comment]
Closes this with the release of [v4.2.3](../releases/tag/v4.2.3)

This is not exactly what's mentioned here but the best I can do

**Pull request closed without merging**
